const ADD_ITEM_TO_BUCKET = "ADD_ITEM_TO_BUCKET";
const DELETE_ITEM_FROM_BUCKET = "DELETE_ITEM_FROM_BUCKET";
const SET_ELEMENT_TO_DELETE = "SET_ELEMENT_TO_DELETE";
const TOGGLE_ELEMENT_TO_PAY = "TOGGLE_ELEMENT_TO_PAY";
const SAVE_FETCHED_BUCKET = "SAVE_FETCHED_BUCKET";
export default {
  ADD_ITEM_TO_BUCKET,
  DELETE_ITEM_FROM_BUCKET,
  SET_ELEMENT_TO_DELETE,
  TOGGLE_ELEMENT_TO_PAY,
  SAVE_FETCHED_BUCKET,
};
