const ADD_ESPRESSO = "ADD_ESPRESSO";
const ADD_MILK = "ADD_MILK";
const DELETE_ESPRESSO = "DELETE_ESPRESSO";
const DELETE_MILK = "DELETE_MILK";
const TOGGLE_CHOCOLATE = "TOGGLE_CHOCOLATE";
const SET_PRESET_OF_COFFEE = 'SET_PRESET_OF_COFFEE'
export default {
  ADD_ESPRESSO,
  TOGGLE_CHOCOLATE,
  ADD_MILK,
  DELETE_ESPRESSO,
  DELETE_MILK,
  SET_PRESET_OF_COFFEE
};
